name: Deploy QIT Docs

on:
  push:
    branches:
      - 24-03/doc-suggestions

jobs:
  deploy:
    runs-on: ubuntu-latest  # or another environment of your choice

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # specify your PHP version here

      - name: Zip Project Contents
        run: |
          zip -r ${{ github.workspace }}/docs.zip . -x "*.git*"

      - name: Deploy QIT Docs
        run: |
          php .github/workflows/scripts/deploy.php
        env:
          DEPLOY_ENDPOINT: ${{ secrets.DEPLOY_ENDPOINT }}
          DOCS_SECRET: ${{ secrets.DOCS_SECRET }}
          FILE: ${{ github.workspace }}/docs.zip
